### ISSUE TITLE
removeSelf is deprecated

### ISSUE THREAD

**Issue by Graf009** [postcss/postcss-use#9] opened 2015-11-10 06:07 UTC
Node#removeSelf is deprecated. Use Node#remove.

https://github.com/postcss/postcss-use/search?utf8=%E2%9C%93&q=removeSelf

**Comment by noderat** [comment] 2015-11-11 05:42
Confirmed fixed after merge of #10 into master. Looks ready to be closed and a version bump.

**Comment by ben-eb** [comment] 2015-11-11 12:40
@noderat Agreed, but the current tests fail locally due to the way that they configure autoprefixer. Patches are welcome.

**Comment by ben-eb** [comment] 2016-01-09 01:55
Released in https://github.com/postcss/postcss-use/commit/e6ce5c4cebd48763c4e21c0aea40fa6f73fff88c.

Sorry for the delay, had other priorities. :smiley:

**Closed by ben-eb** 2016-01-09 01:55 UTC
Labels: bug
